### ISSUE TITLE
ci(release): La version du tag doit être la référence pour le package NPM et la Release GitHub.

### ISSUE THREAD

**Issue by lowzonenose** [IGNF/geopf-extensions-openlayers#135]
Le processus de release est déclenché par la création d'un tag. 
La version du tag doit être la référence pour le package NPM ainsi que sur la Release GitHub.
Actuellement, la version du package et de la Release GitHub est issue du **package.json**.

Via les github actions,
* [x] modifier la version du package.json 
```yaml
# job build
- name: Build package
        run: npm run publish --version=${{ github.ref_name }}
```
:warning: choix de ne pas **commiter** la modification

* [x] modifier la version du ChangeLog 
```yaml
# job release
- name: Create ChangeLog
        run: |
          sed -i 's/__VERSION__/${{ github.ref_name }}/g' DRAFT_CHANGELOG.md
          sed -i 's/__DATE__/${{ steps.date.outputs.date }}/g' DRAFT_CHANGELOG.md
```
